version: '3.8'
services:
  auth_service:
    build: ./services/auth_service
    container_name: auth_service
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
    depends_on:
      - postgres
      - redis
      - kafka

  user_management_service:
    build: ./services/user_management_service
    container_name: user_management_service
    ports:
      - "8002:8000"
    environment:
      - POSTGRES_DB=user_management_db
      - POSTGRES_USER=user_management_user
      - POSTGRES_PASSWORD=user_management_pass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
