# Generated by Django 4.2.16 on 2024-10-09 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('from_account_id', models.IntegerField()),
                ('to_account_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PAYMENT', 'Payment')], max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
