# Generated by Django 5.1.1 on 2024-11-29 14:17

import django.db.models.deletion
import userprofile.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('full_name', models.CharField(max_length=255, validators=[userprofile.utils.validators.validate_full_name])),
                ('tax_number', models.CharField(max_length=50, unique=True, validators=[userprofile.utils.validators.validate_tax_number])),
                ('phone_number', models.CharField(max_length=20, validators=[userprofile.utils.validators.validate_phone_number])),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['user_id'], name='user_profil_user_id_fbe33d_idx'), models.Index(fields=['tax_number'], name='user_profil_tax_num_b6e087_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('IDENTITY_CARD', 'Identity Card'), ('DRIVING_LICENSE', 'Driving License'), ('TAX_ID', 'Tax ID Card')], max_length=50)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('verification_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='userprofile.userprofile')),
            ],
            options={
                'db_table': 'user_documents',
                'indexes': [models.Index(fields=['profile'], name='user_docume_profile_0ec2ba_idx'), models.Index(fields=['document_number'], name='user_docume_documen_3bb873_idx'), models.Index(fields=['verification_status'], name='user_docume_verific_04397e_idx')],
            },
        ),
    ]
