# Generated by Django 4.2.16 on 2024-10-10 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.IntegerField()),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('MORTGAGE', 'Mortgage'), ('VEHICLE', 'Vehicle')], max_length=10)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='APPLIED', max_length=10)),
                ('collateral_details', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
