# Generated by Django 5.1.1 on 2024-11-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_role_name_role_name_user_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
