name: Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Deploy with Docker Compose
    #   run: |
    #     docker-compose -f docker-compose.prod.yml up -d
    #   env:
        # ACCOUNT_DB_PASSWORD: ${{ secrets.ACCOUNT_DB_PASSWORD }}
        # AUDIT_DB_PASSWORD: ${{ secrets.AUDIT_DB_PASSWORD }}
        # AUTH_DB_PASSWORD: ${{ secrets.AUTH_DB_PASSWORD }}
        # CARD_DB_PASSWORD: ${{ secrets.CARD_DB_PASSWORD }}
        # LOAN_DB_PASSWORD: ${{ secrets.LOAN_DB_PASSWORD }}
        # TRANSACTION_DB_PASSWORD: ${{ secrets.TRANSACTION_DB_PASSWORD }}
        # USER_DB_PASSWORD: ${{ secrets.USER_DB_PASSWORD }}
        # PAYMENT_DB_PASSWORD: ${{ secrets.PAYMENT_DB_PASSWORD }}
        
        # SECRET_KEY_ACCOUNT_SERVICE: ${{ secrets.SECRET_KEY_ACCOUNT_SERVICE }}
        # SECRET_KEY_AUDIT_SERVICE: ${{ secrets.SECRET_KEY_AUDIT_SERVICE }}
        # SECRET_KEY_AUTH_SERVICE: ${{ secrets.SECRET_KEY_AUTH_SERVICE }}
        # SECRET_KEY_CARD_SERVICE: ${{ secrets.SECRET_KEY_CARD_SERVICE }}
        # SECRET_KEY_FRAUD_SERVICE: ${{ secrets.SECRET_KEY_FRAUD_SERVICE }}
        # SECRET_KEY_LOAN_SERVICE: ${{ secrets.SECRET_KEY_LOAN_SERVICE }}
        # SECRET_KEY_NOTIFICATION_SERVICE: ${{ secrets.SECRET_KEY_NOTIFICATION_SERVICE }}
        # SECRET_KEY_PAYMENT_SERVICE: ${{ secrets.SECRET_KEY_PAYMENT_SERVICE }}
        # SECRET_KEY_SUPPORT_SERVICE: ${{ secrets.SECRET_KEY_SUPPORT_SERVICE }}
        # SECRET_KEY_TRANSACTION_SERVICE: ${{ secrets.SECRET_KEY_TRANSACTION_SERVICE }}
        # SECRET_KEY_USER_SERVICE: ${{ secrets.SECRET_KEY_USER_SERVICE }}

        # MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        # MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
        # REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        # POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD}}

