# .github/workflows/deploy.yml

name: Deploy to Docker Hub and Run Docker Compose

on:
  push:
    branches:
      - main  # Ubah ke nama branch utama Anda jika berbeda

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker images for Microservices
      - name: Build and push Auth Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/auth_service
          file: ./microservices/services/auth_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-auth_service:latest
          build-args: |
            SECRET_KEY_AUTH_SERVICE=${{ secrets.SECRET_KEY_AUTH_SERVICE }}
            AUTH_DB_PASSWORD=${{ secrets.AUTH_DB_PASSWORD }}

      - name: Build and push User Management Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/user_management_service
          file: ./microservices/services/user_management_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-user_management_service:latest
          build-args: |
            SECRET_KEY_USER_SERVICE=${{ secrets.SECRET_KEY_USER_SERVICE }}
            USER_DB_PASSWORD=${{ secrets.USER_DB_PASSWORD }}

      - name: Build and push Account Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/account_service
          file: ./microservices/services/account_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-account_service:latest
          build-args: |
            SECRET_KEY_ACCOUNT_SERVICE=${{ secrets.SECRET_KEY_ACCOUNT_SERVICE }}
            ACCOUNT_DB_PASSWORD=${{ secrets.ACCOUNT_DB_PASSWORD }}

      - name: Build and push Transaction Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/transaction_service
          file: ./microservices/services/transaction_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-transaction_service:latest
          build-args: |
            SECRET_KEY_TRANSACTION_SERVICE=${{ secrets.SECRET_KEY_TRANSACTION_SERVICE }}
            TRANSACTION_DB_PASSWORD=${{ secrets.TRANSACTION_DB_PASSWORD }}

      - name: Build and push Payment Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/payment_service
          file: ./microservices/services/payment_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-payment_service:latest
          build-args: |
            SECRET_KEY_PAYMENT_SERVICE=${{ secrets.SECRET_KEY_PAYMENT_SERVICE }}
            PAYMENT_DB_PASSWORD=${{ secrets.PAYMENT_DB_PASSWORD }}

      - name: Build and push Card Management Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/card_management_service
          file: ./microservices/services/card_management_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-card_management_service:latest
          build-args: |
            SECRET_KEY_CARD_SERVICE=${{ secrets.SECRET_KEY_CARD_SERVICE }}
            CARD_DB_PASSWORD=${{ secrets.CARD_DB_PASSWORD }}

      - name: Build and push Loan Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/loan_service
          file: ./microservices/services/loan_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-loan_service:latest
          build-args: |
            SECRET_KEY_LOAN_SERVICE=${{ secrets.SECRET_KEY_LOAN_SERVICE }}
            LOAN_DB_PASSWORD=${{ secrets.LOAN_DB_PASSWORD }}

      - name: Build and push Notification Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/notification_service
          file: ./microservices/services/notification_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-notification_service:latest
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY_NOTIFICATION_SERVICE }}
            MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}

      - name: Build and push Audit Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/audit_service
          file: ./microservices/services/audit_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-audit_service:latest
          build-args: |
            SECRET_KEY_AUDIT_SERVICE=${{ secrets.SECRET_KEY_AUDIT_SERVICE }}
            MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}

      - name: Build and push Fraud Detection Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/fraud_detection_service
          file: ./microservices/services/fraud_detection_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-fraud_detection_service:latest
          build-args: |
            SECRET_KEY_FRAUD_SERVICE=${{ secrets.SECRET_KEY_FRAUD_SERVICE }}
            MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}

      - name: Build and push Support Service
        uses: docker/build-push-action@v4
        with:
          context: ./microservices/services/support_service
          file: ./microservices/services/support_service/Dockerfile
          push: true
          tags: akmaleyzal/luminacerisbank-support_service:latest
          build-args: |
            SECRET_KEY_SUPPORT_SERVICE=${{ secrets.SECRET_KEY_SUPPORT_SERVICE }}
            MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}

      # Step 4: Build and push Docker images for Microfrontends
      - name: Build and push Login Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/login_page/login
          push: true
          tags: akmaleyzal/luminacerisbank-login_page:latest

      - name: Build and push Home Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/home_page/home
          push: true
          tags: akmaleyzal/luminacerisbank-home_page:latest

      - name: Build and push Card Management Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/cardManagement_page/card
          push: true
          tags: akmaleyzal/luminacerisbank-cardmanagement_page:latest

      - name: Build and push Fraud Alert Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/fraudAlert_page/fraud
          push: true
          tags: akmaleyzal/luminacerisbank-fraudalert_page:latest

      - name: Build and push History Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/history_page/history
          push: true
          tags: akmaleyzal/luminacerisbank-history_page:latest

      - name: Build and push Loan Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/loan_page/loan
          push: true
          tags: akmaleyzal/luminacerisbank-loan_page:latest

      - name: Build and push Notification Center Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/notificationCenter_page/notification
          push: true
          tags: akmaleyzal/luminacerisbank-notificationcenter_page:latest

      - name: Build and push Payment Service Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/paymentService_page/payment
          push: true
          tags: akmaleyzal/luminacerisbank-paymentservice_page:latest

      - name: Build and push Profile Setting Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/profileSetting_page/profile
          push: true
          tags: akmaleyzal/luminacerisbank-profilesetting_page:latest

      - name: Build and push Support Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/support_page/support
          push: true
          tags: akmaleyzal/luminacerisbank-support_page:latest

      - name: Build and push Transfer Page
        uses: docker/build-push-action@v4
        with:
          context: ./micro-frontend/frontend/transfer_page/transfer
          push: true
          tags: akmaleyzal/luminacerisbank-transfer_page:latest

      # Step 5: Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: | 
          docker-compose -f docker-compose.yml down -v
          docker-compose -f docker-compose.yml up -d --build
        env:
          ACCOUNT_DB_PASSWORD: ${{ secrets.ACCOUNT_DB_PASSWORD }}
          AUDIT_DB_PASSWORD: ${{ secrets.AUDIT_DB_PASSWORD }}
          AUTH_DB_PASSWORD: ${{ secrets.AUTH_DB_PASSWORD }}
          CARD_DB_PASSWORD: ${{ secrets.CARD_DB_PASSWORD }}
          LOAN_DB_PASSWORD: ${{ secrets.LOAN_DB_PASSWORD }}
          TRANSACTION_DB_PASSWORD: ${{ secrets.TRANSACTION_DB_PASSWORD }}
          USER_DB_PASSWORD: ${{ secrets.USER_DB_PASSWORD }}
          PAYMENT_DB_PASSWORD: ${{ secrets.PAYMENT_DB_PASSWORD }}
          
          SECRET_KEY_ACCOUNT_SERVICE: ${{ secrets.SECRET_KEY_ACCOUNT_SERVICE }}
          SECRET_KEY_AUDIT_SERVICE: ${{ secrets.SECRET_KEY_AUDIT_SERVICE }}
          SECRET_KEY_AUTH_SERVICE: ${{ secrets.SECRET_KEY_AUTH_SERVICE }}
          SECRET_KEY_CARD_SERVICE: ${{ secrets.SECRET_KEY_CARD_SERVICE }}
          SECRET_KEY_FRAUD_SERVICE: ${{ secrets.SECRET_KEY_FRAUD_SERVICE }}
          SECRET_KEY_LOAN_SERVICE: ${{ secrets.SECRET_KEY_LOAN_SERVICE }}
          SECRET_KEY_NOTIFICATION_SERVICE: ${{ secrets.SECRET_KEY_NOTIFICATION_SERVICE }}
          SECRET_KEY_PAYMENT_SERVICE: ${{ secrets.SECRET_KEY_PAYMENT_SERVICE }}
          SECRET_KEY_SUPPORT_SERVICE: ${{ secrets.SECRET_KEY_SUPPORT_SERVICE }}
          SECRET_KEY_TRANSACTION_SERVICE: ${{ secrets.SECRET_KEY_TRANSACTION_SERVICE }}
          SECRET_KEY_USER_SERVICE: ${{ secrets.SECRET_KEY_USER_SERVICE }}
    
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}

          CONFLUENT_BOOTSTRAP_SERVERS: ${{ secrets.CONFLUENT_BOOTSTRAP_SERVERS }}
          CONFLUENT_SASL_USERNAME: ${{ secrets.CONFLUENT_SASL_USERNAME }}
          CONFLUENT_SASL_PASSWORD: ${{ secrets.CONFLUENT_SASL_PASSWORD }}
          CONFLUENT_CLIENT_ID: ${{ secrets.CONFLUENT_CLIENT_ID }}
